# CMake generated Testfile for 
# Source directory: E:/Repositories/Gladiator-Bot-reverse/tests/aas
# Build directory: E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/aas
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(aas_map "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/aas/Debug/aas_map_tests.exe")
  set_tests_properties(aas_map PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;23;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(aas_map "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/aas/Release/aas_map_tests.exe")
  set_tests_properties(aas_map PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;23;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(aas_map "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/aas/MinSizeRel/aas_map_tests.exe")
  set_tests_properties(aas_map PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;23;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(aas_map "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/aas/RelWithDebInfo/aas_map_tests.exe")
  set_tests_properties(aas_map PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;23;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;0;")
else()
  add_test(aas_map NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(aas_debug_lines "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/aas/Debug/aas_debug_line_tests.exe")
  set_tests_properties(aas_debug_lines PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;40;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(aas_debug_lines "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/aas/Release/aas_debug_line_tests.exe")
  set_tests_properties(aas_debug_lines PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;40;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(aas_debug_lines "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/aas/MinSizeRel/aas_debug_line_tests.exe")
  set_tests_properties(aas_debug_lines PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;40;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(aas_debug_lines "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/aas/RelWithDebInfo/aas_debug_line_tests.exe")
  set_tests_properties(aas_debug_lines PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;40;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;0;")
else()
  add_test(aas_debug_lines NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(aas_reach_pass_areas "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/aas/Debug/aas_reach_pass_area_tests.exe")
  set_tests_properties(aas_reach_pass_areas PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;57;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(aas_reach_pass_areas "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/aas/Release/aas_reach_pass_area_tests.exe")
  set_tests_properties(aas_reach_pass_areas PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;57;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(aas_reach_pass_areas "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/aas/MinSizeRel/aas_reach_pass_area_tests.exe")
  set_tests_properties(aas_reach_pass_areas PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;57;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(aas_reach_pass_areas "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/aas/RelWithDebInfo/aas_reach_pass_area_tests.exe")
  set_tests_properties(aas_reach_pass_areas PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;57;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/aas/CMakeLists.txt;0;")
else()
  add_test(aas_reach_pass_areas NOT_AVAILABLE)
endif()
