# CMake generated Testfile for 
# Source directory: C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity
# Build directory: C:/Users/djdac/source/repos/gladiator-bot-reverse/build-clang/tests/parity
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(botlib_parity_bot_interface "C:/Users/djdac/source/repos/gladiator-bot-reverse/build-clang/tests/parity/botlib_parity_bot_interface.exe")
set_tests_properties(botlib_parity_bot_interface PROPERTIES  FIXTURES_REQUIRED "parity_assets" LABELS "Parity" _BACKTRACE_TRIPLES "C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;22;add_test;C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;31;add_botlib_parity_test;C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;0;")
add_test(botlib_parity_bot_move "C:/Users/djdac/source/repos/gladiator-bot-reverse/build-clang/tests/parity/botlib_parity_bot_move.exe")
set_tests_properties(botlib_parity_bot_move PROPERTIES  FIXTURES_REQUIRED "parity_assets" LABELS "Parity" _BACKTRACE_TRIPLES "C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;22;add_test;C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;34;add_botlib_parity_test;C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;0;")
add_test(botlib_parity_precompiler_lexer "C:/Users/djdac/source/repos/gladiator-bot-reverse/build-clang/tests/parity/botlib_parity_precompiler_lexer.exe")
set_tests_properties(botlib_parity_precompiler_lexer PROPERTIES  FIXTURES_REQUIRED "parity_assets" LABELS "Parity" _BACKTRACE_TRIPLES "C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;22;add_test;C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;37;add_botlib_parity_test;C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;0;")
add_test(botlib_parity_aas_debug "C:/Users/djdac/source/repos/gladiator-bot-reverse/build-clang/tests/parity/botlib_parity_aas_debug.exe")
set_tests_properties(botlib_parity_aas_debug PROPERTIES  FIXTURES_REQUIRED "parity_assets" LABELS "Parity" _BACKTRACE_TRIPLES "C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;22;add_test;C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;40;add_botlib_parity_test;C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;0;")
add_test(botlib_parity_bridge "C:/Users/djdac/source/repos/gladiator-bot-reverse/build-clang/tests/parity/botlib_parity_bridge.exe")
set_tests_properties(botlib_parity_bridge PROPERTIES  FIXTURES_REQUIRED "parity_assets" LABELS "Parity" _BACKTRACE_TRIPLES "C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;22;add_test;C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;43;add_botlib_parity_test;C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;0;")
add_test(botlib_parity_update_translator "C:/Users/djdac/source/repos/gladiator-bot-reverse/build-clang/tests/parity/botlib_parity_update_translator.exe")
set_tests_properties(botlib_parity_update_translator PROPERTIES  FIXTURES_REQUIRED "parity_assets" LABELS "Parity" _BACKTRACE_TRIPLES "C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;22;add_test;C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;48;add_botlib_parity_test;C:/Users/djdac/source/repos/gladiator-bot-reverse/tests/parity/CMakeLists.txt;0;")
