# CMake generated Testfile for 
# Source directory: E:/Repositories/Gladiator-Bot-reverse/tests/ai
# Build directory: E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ai_character "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/Debug/ai_character_tests.exe")
  set_tests_properties(ai_character PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;26;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ai_character "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/Release/ai_character_tests.exe")
  set_tests_properties(ai_character PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;26;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ai_character "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/MinSizeRel/ai_character_tests.exe")
  set_tests_properties(ai_character PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;26;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ai_character "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/RelWithDebInfo/ai_character_tests.exe")
  set_tests_properties(ai_character PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;26;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
else()
  add_test(ai_character NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ai_goal_move "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/Debug/ai_goal_move_tests.exe")
  set_tests_properties(ai_goal_move PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;29;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ai_goal_move "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/Release/ai_goal_move_tests.exe")
  set_tests_properties(ai_goal_move PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;29;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ai_goal_move "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/MinSizeRel/ai_goal_move_tests.exe")
  set_tests_properties(ai_goal_move PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;29;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ai_goal_move "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/RelWithDebInfo/ai_goal_move_tests.exe")
  set_tests_properties(ai_goal_move PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;29;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
else()
  add_test(ai_goal_move NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ai_weight "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/Debug/ai_weight_tests.exe")
  set_tests_properties(ai_weight PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;32;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ai_weight "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/Release/ai_weight_tests.exe")
  set_tests_properties(ai_weight PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;32;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ai_weight "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/MinSizeRel/ai_weight_tests.exe")
  set_tests_properties(ai_weight PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;32;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ai_weight "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/RelWithDebInfo/ai_weight_tests.exe")
  set_tests_properties(ai_weight PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;32;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
else()
  add_test(ai_weight NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ai_weapon "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/Debug/ai_weapon_tests.exe")
  set_tests_properties(ai_weapon PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;35;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ai_weapon "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/Release/ai_weapon_tests.exe")
  set_tests_properties(ai_weapon PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;35;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ai_weapon "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/MinSizeRel/ai_weapon_tests.exe")
  set_tests_properties(ai_weapon PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;35;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ai_weapon "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/RelWithDebInfo/ai_weapon_tests.exe")
  set_tests_properties(ai_weapon PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;35;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
else()
  add_test(ai_weapon NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ai_dm "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/Debug/ai_dm_tests.exe")
  set_tests_properties(ai_dm PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;49;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ai_dm "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/Release/ai_dm_tests.exe")
  set_tests_properties(ai_dm PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;49;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ai_dm "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/MinSizeRel/ai_dm_tests.exe")
  set_tests_properties(ai_dm PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;49;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ai_dm "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/RelWithDebInfo/ai_dm_tests.exe")
  set_tests_properties(ai_dm PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;49;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
else()
  add_test(ai_dm NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ai_move "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/Debug/ai_move_tests.exe")
  set_tests_properties(ai_move PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;61;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ai_move "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/Release/ai_move_tests.exe")
  set_tests_properties(ai_move PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;61;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ai_move "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/MinSizeRel/ai_move_tests.exe")
  set_tests_properties(ai_move PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;61;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ai_move "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/ai/RelWithDebInfo/ai_move_tests.exe")
  set_tests_properties(ai_move PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;61;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/ai/CMakeLists.txt;0;")
else()
  add_test(ai_move NOT_AVAILABLE)
endif()
