//===========================================================================
//
// Name:				babe_c.c
// Function:		characteristics for the Silicon Babe character
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990517b
// Tab Size:		3 (real tabs)
// Notes				See defaul_c.c for an explanation of definitions
//===========================================================================

#include "chars.h"

character "babe"
{
	CHARACTERISTIC_NAME						"Silicon Babe"
	CHARACTERISTIC_ALT_NAME					"Epsilon"
	CHARACTERISTIC_GENDER					"female"
	CHARACTERISTIC_CHAT_FILE				"bots/babe_t.c"
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/babe_w.c"
	CHARACTERISTIC_ITEMWEIGHTS				"bots/babe_i.c"
	CHARACTERISTIC_REACTIONTIME			0.01
	CHARACTERISTIC_ATTACK_SKILL			0.85
	CHARACTERISTIC_AIM_SKILL				0.92
	CHARACTERISTIC_AIM_ACCURACY			0.82
	CHARACTERISTIC_VIEW_ACCELERATION		400
	CHARACTERISTIC_VIEW_DEACCELERATION	500
	CHARACTERISTIC_CROUCHER					0.05
	CHARACTERISTIC_JUMPER					0.78
	CHARACTERISTIC_WEAPONJUMPING			0.88
	CHARACTERISTIC_GRAPPLE_USER			1
	CHARACTERISTIC_VENGEFULNESS			0.9
	CHARACTERISTIC_AGGRESSION				0.7
	CHARACTERISTIC_FEAR						0.3
	CHARACTERISTIC_SELFPRESERVATION		0.7
	CHARACTERISTIC_BUTTKISSER				0
	CHARACTERISTIC_FRUSTRATEDNESS			0.1
	CHARACTERISTIC_EASY_FRAGGER			0.4
	CHARACTERISTIC_ALERTNESS				0.6
	CHARACTERISTIC_TELEFRAGAWARE			0.4
	CHARACTERISTIC_CAMPER					0.3
	CHARACTERISTIC_EGO						0.8
	CHARACTERISTIC_TEAMSPIRIT				0.6
	CHARACTERISTIC_WEAPONSWITCHER			0.3
	CHARACTERISTIC_SKIN_SWITCHER			0
	CHARACTERISTIC_NAME_SWITCHER			0
//===========================================================================
	CHARACTERISTIC_CHAT_NAME				"babe"
	CHARACTERISTIC_CHAT_CPM					400
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.6
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.66
	CHARACTERISTIC_CHAT_REPLY				0.34
	CHARACTERISTIC_CHAT_DEATH				0.4
	CHARACTERISTIC_CHAT_KILL				0.8
	CHARACTERISTIC_CHAT_INSULT				0.62
	CHARACTERISTIC_CHAT_MISC				0.6
	CHARACTERISTIC_CHAT_RANDOM				0.15
//===========================================================================
	CHARACTERISTIC_PIZZAPREFERENCE		0
	CHARACTERISTIC_CALL_PRONE				0
	CHARACTERISTIC_BEDDY_BYE_TIME			0.01
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0.6
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_CONTROLTYPE				2
} //end character babe

