//===========================================================================
//
// Name:				bill_c.c
// Function:		characteristics for Bill Gates bot character
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990517b
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "bill"
{
	CHARACTERISTIC_NAME						"Bill Gates"
	CHARACTERISTIC_ALT_NAME					"Beta"
	CHARACTERISTIC_GENDER					"male"
	CHARACTERISTIC_CHAT_FILE				"bots/bill_t.c"
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/bill_w.c"
	CHARACTERISTIC_ITEMWEIGHTS				"bots/bill_i.c"
	CHARACTERISTIC_REACTIONTIME			0.1
	CHARACTERISTIC_ATTACK_SKILL			0.9
	CHARACTERISTIC_AIM_SKILL				0.60
	CHARACTERISTIC_AIM_ACCURACY			0.30
	CHARACTERISTIC_VIEW_ACCELERATION		250
	CHARACTERISTIC_VIEW_DEACCELERATION	260
	CHARACTERISTIC_CROUCHER					0.5
	CHARACTERISTIC_JUMPER					0.65
	CHARACTERISTIC_WEAPONJUMPING			0.8
	CHARACTERISTIC_GRAPPLE_USER			0.9
	CHARACTERISTIC_VENGEFULNESS			1
	CHARACTERISTIC_AGGRESSION				1
	CHARACTERISTIC_FEAR						0.2
	CHARACTERISTIC_SELFPRESERVATION		0.1
	CHARACTERISTIC_BUTTKISSER				0
	CHARACTERISTIC_FRUSTRATEDNESS			0.88
	CHARACTERISTIC_EASY_FRAGGER			1
	CHARACTERISTIC_ALERTNESS				0.25
	CHARACTERISTIC_TELEFRAGAWARE			0.1
	CHARACTERISTIC_CAMPER					0.7
	CHARACTERISTIC_EGO						1
	CHARACTERISTIC_TEAMSPIRIT				0.1
	CHARACTERISTIC_WEAPONSWITCHER			0.5
	CHARACTERISTIC_SKIN_SWITCHER			0
	CHARACTERISTIC_NAME_SWITCHER			0
//===========================================================================
	CHARACTERISTIC_CHAT_NAME				"bill"
	CHARACTERISTIC_CHAT_CPM					200
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.91
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.89
	CHARACTERISTIC_CHAT_REPLY				0.70
	CHARACTERISTIC_CHAT_DEATH				0.30
	CHARACTERISTIC_CHAT_KILL				0.88
	CHARACTERISTIC_CHAT_INSULT				0.80
	CHARACTERISTIC_CHAT_MISC				0.42
	CHARACTERISTIC_CHAT_RANDOM				0.10
//===========================================================================
	CHARACTERISTIC_PIZZAPREFERENCE		0
	CHARACTERISTIC_CALL_PRONE				0
	CHARACTERISTIC_BEDDY_BYE_TIME			0.07
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		1
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_CONTROLTYPE				2
} //end character bill gates

