//===========================================================================
//
// Name:				bitch_c.c
// Function:		characteristics for Quad Bitch character
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990510a
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "bitch"
{
	CHARACTERISTIC_NAME						"Quad Bitch"
	CHARACTERISTIC_ALT_NAME					"Labda"
	CHARACTERISTIC_GENDER					"female"
	CHARACTERISTIC_CHAT_FILE				"bots/bitch_t.c"
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/bitch_w.c"
	CHARACTERISTIC_ITEMWEIGHTS				"bots/bitch_i.c"
	CHARACTERISTIC_REACTIONTIME			0.8
	CHARACTERISTIC_ATTACK_SKILL			0.2
	CHARACTERISTIC_AIM_SKILL				0.6
	CHARACTERISTIC_AIM_ACCURACY			1
	CHARACTERISTIC_VIEW_ACCELERATION		1000
	CHARACTERISTIC_VIEW_DEACCELERATION	1255
	CHARACTERISTIC_CROUCHER					0.1
	CHARACTERISTIC_JUMPER					1
	CHARACTERISTIC_WEAPONJUMPING			0.89
	CHARACTERISTIC_GRAPPLE_USER			0.5
	CHARACTERISTIC_VENGEFULNESS			0.70
	CHARACTERISTIC_AGGRESSION				0
	CHARACTERISTIC_FEAR						0
	CHARACTERISTIC_SELFPRESERVATION		0.2
	CHARACTERISTIC_BUTTKISSER				0
	CHARACTERISTIC_FRUSTRATEDNESS			0.12
	CHARACTERISTIC_EASY_FRAGGER			0.1
	CHARACTERISTIC_ALERTNESS				1
	CHARACTERISTIC_TELEFRAGAWARE			0
	CHARACTERISTIC_CAMPER					0.8
	CHARACTERISTIC_EGO						0.44
	CHARACTERISTIC_TEAMSPIRIT				0.88
	CHARACTERISTIC_WEAPONSWITCHER			1
	CHARACTERISTIC_SKIN_SWITCHER			1
	CHARACTERISTIC_NAME_SWITCHER			0.44
//===========================================================================
	CHARACTERISTIC_CHAT_NAME				"bitch"
	CHARACTERISTIC_CHAT_CPM					66
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.6
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.3
	CHARACTERISTIC_CHAT_REPLY				0.1
	CHARACTERISTIC_CHAT_DEATH				0.4
	CHARACTERISTIC_CHAT_KILL				1
	CHARACTERISTIC_CHAT_INSULT				0
	CHARACTERISTIC_CHAT_MISC				0.5
	CHARACTERISTIC_CHAT_RANDOM				0.25
//===========================================================================
	CHARACTERISTIC_PIZZAPREFERENCE		0.03
	CHARACTERISTIC_CALL_PRONE				0
	CHARACTERISTIC_BEDDY_BYE_TIME			0
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0.6
	CHARACTERISTIC_3DACCELERATOR			0
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_CONTROLTYPE				1
} //end character bitch


