//===========================================================================
//
// Name:				byte_c.c
// Function:		characteristics for bots
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990517a
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "byte" 
{
	CHARACTERISTIC_NAME						"Byte"
	CHARACTERISTIC_ALT_NAME					"Iota"
	CHARACTERISTIC_GENDER					"other"
	CHARACTERISTIC_CHAT_FILE				"bots/byte_t.c"
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/byte_w.c"
	CHARACTERISTIC_ITEMWEIGHTS				"bots/byte_i.c"
	CHARACTERISTIC_REACTIONTIME			0.85
	CHARACTERISTIC_ATTACK_SKILL			0.15
	CHARACTERISTIC_AIM_SKILL				0.15
	CHARACTERISTIC_AIM_ACCURACY			0.15
	CHARACTERISTIC_VIEW_ACCELERATION		150
	CHARACTERISTIC_VIEW_DEACCELERATION	150
	CHARACTERISTIC_CROUCHER					0.1
	CHARACTERISTIC_JUMPER					0.6
	CHARACTERISTIC_WEAPONJUMPING			1
	CHARACTERISTIC_GRAPPLE_USER			0.15
	CHARACTERISTIC_VENGEFULNESS			1
	CHARACTERISTIC_AGGRESSION				0.44
	CHARACTERISTIC_FEAR						0.6
	CHARACTERISTIC_SELFPRESERVATION		1
	CHARACTERISTIC_BUTTKISSER				0
	CHARACTERISTIC_FRUSTRATEDNESS			0.8
	CHARACTERISTIC_EASY_FRAGGER			0.32
	CHARACTERISTIC_ALERTNESS				0.87
	CHARACTERISTIC_TELEFRAGAWARE			0.5
	CHARACTERISTIC_CAMPER					0.38
	CHARACTERISTIC_EGO						0.15
	CHARACTERISTIC_TEAMSPIRIT				1
	CHARACTERISTIC_WEAPONSWITCHER			0.55
	CHARACTERISTIC_SKIN_SWITCHER			1
	CHARACTERISTIC_NAME_SWITCHER			1
//===========================================================================
	CHARACTERISTIC_CHAT_NAME				"byte"
	CHARACTERISTIC_CHAT_CPM					300
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.88
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.67
	CHARACTERISTIC_CHAT_REPLY				0.34
	CHARACTERISTIC_CHAT_DEATH				0.84
	CHARACTERISTIC_CHAT_KILL				0.30
	CHARACTERISTIC_CHAT_INSULT				0.70
	CHARACTERISTIC_CHAT_MISC				0.40
	CHARACTERISTIC_CHAT_RANDOM				0.23
//===========================================================================
	CHARACTERISTIC_PIZZAPREFERENCE		0.03
	CHARACTERISTIC_CALL_PRONE				0
	CHARACTERISTIC_BEDDY_BYE_TIME			0
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0.1
	CHARACTERISTIC_3DACCELERATOR			0
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_CONTROLTYPE				0
} //end character byte


