//===========================================================================
//
// Name:				hunk_c.c
// Function:		characteristics for adrenaline hunk char.
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990517a
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "hunk"
{
	CHARACTERISTIC_NAME						"Adrenaline Hunk"
	CHARACTERISTIC_ALT_NAME					"Zeta"
	CHARACTERISTIC_GENDER					"male"
	CHARACTERISTIC_CHAT_FILE				"bots/hunk_t.c"
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/hunk_w.c"
	CHARACTERISTIC_ITEMWEIGHTS				"bots/hunk_i.c"
	CHARACTERISTIC_REACTIONTIME			0.3
	CHARACTERISTIC_ATTACK_SKILL			0.70
	CHARACTERISTIC_AIM_SKILL				1
	CHARACTERISTIC_AIM_ACCURACY			0.5
	CHARACTERISTIC_VIEW_ACCELERATION		360
	CHARACTERISTIC_VIEW_DEACCELERATION	600
	CHARACTERISTIC_CROUCHER					0.225
	CHARACTERISTIC_JUMPER					0.75
	CHARACTERISTIC_WEAPONJUMPING			0.50
	CHARACTERISTIC_GRAPPLE_USER			0.8
	CHARACTERISTIC_VENGEFULNESS			0.15
	CHARACTERISTIC_AGGRESSION				0.10
	CHARACTERISTIC_FEAR						0.10
	CHARACTERISTIC_SELFPRESERVATION		0.20
	CHARACTERISTIC_BUTTKISSER				0
	CHARACTERISTIC_FRUSTRATEDNESS			0
	CHARACTERISTIC_EASY_FRAGGER			0.85
	CHARACTERISTIC_ALERTNESS				0.75
	CHARACTERISTIC_TELEFRAGAWARE			0.65
	CHARACTERISTIC_CAMPER					0.01
	CHARACTERISTIC_EGO						0.30
	CHARACTERISTIC_TEAMSPIRIT				1
	CHARACTERISTIC_WEAPONSWITCHER			0.75
	CHARACTERISTIC_SKIN_SWITCHER			0.8
	CHARACTERISTIC_NAME_SWITCHER			1
//===========================================================================
	CHARACTERISTIC_CHAT_NAME				"hunk"
	CHARACTERISTIC_CHAT_CPM					100
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.84
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.86
	CHARACTERISTIC_CHAT_REPLY				0.54
	CHARACTERISTIC_CHAT_DEATH				0.01
	CHARACTERISTIC_CHAT_KILL				1
	CHARACTERISTIC_CHAT_INSULT				0.05
	CHARACTERISTIC_CHAT_MISC				0.45
	CHARACTERISTIC_CHAT_RANDOM				0.26
//===========================================================================
	CHARACTERISTIC_PIZZAPREFERENCE		0.01
	CHARACTERISTIC_CALL_PRONE				0.01
	CHARACTERISTIC_BEDDY_BYE_TIME			0.01
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0
	CHARACTERISTIC_3DACCELERATOR			0
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_CONTROLTYPE				0
} //end character hunk
