//===========================================================================
//
// Name:				java_c.c
// Function:		characteristics for Java man
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990517a
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "java"
{
	CHARACTERISTIC_NAME						"Java Man"
	CHARACTERISTIC_ALT_NAME					"Alpha"
	CHARACTERISTIC_GENDER					"other"
	CHARACTERISTIC_CHAT_FILE				"bots/java_t.c"
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/java_w.c"
	CHARACTERISTIC_ITEMWEIGHTS				"bots/java_i.c"
	CHARACTERISTIC_REACTIONTIME			0.25
	CHARACTERISTIC_ATTACK_SKILL			0.75
	CHARACTERISTIC_AIM_SKILL				0.1
	CHARACTERISTIC_AIM_ACCURACY			1
	CHARACTERISTIC_VIEW_ACCELERATION		100
	CHARACTERISTIC_VIEW_DEACCELERATION	300
	CHARACTERISTIC_CROUCHER					0.01
	CHARACTERISTIC_JUMPER					1
	CHARACTERISTIC_WEAPONJUMPING			0.44
	CHARACTERISTIC_GRAPPLE_USER			0.67
	CHARACTERISTIC_VENGEFULNESS			0.23
	CHARACTERISTIC_AGGRESSION				0.2
	CHARACTERISTIC_FEAR						0.8
	CHARACTERISTIC_SELFPRESERVATION		0.4
	CHARACTERISTIC_BUTTKISSER				0.6
	CHARACTERISTIC_FRUSTRATEDNESS			0.1
	CHARACTERISTIC_EASY_FRAGGER			0.1
	CHARACTERISTIC_ALERTNESS				1
	CHARACTERISTIC_TELEFRAGAWARE			0.76
	CHARACTERISTIC_CAMPER					0.02
	CHARACTERISTIC_EGO						0.50
	CHARACTERISTIC_TEAMSPIRIT				1
	CHARACTERISTIC_WEAPONSWITCHER			1
	CHARACTERISTIC_SKIN_SWITCHER			0.6
	CHARACTERISTIC_NAME_SWITCHER			1
//===========================================================================
	CHARACTERISTIC_CHAT_NAME				"java"
	CHARACTERISTIC_CHAT_CPM					170
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.9
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.23
	CHARACTERISTIC_CHAT_REPLY				0.4
	CHARACTERISTIC_CHAT_DEATH				0.79
	CHARACTERISTIC_CHAT_KILL				1
	CHARACTERISTIC_CHAT_INSULT				0.66
	CHARACTERISTIC_CHAT_MISC				0.44
	CHARACTERISTIC_CHAT_RANDOM				0.79
//===========================================================================
	CHARACTERISTIC_PIZZAPREFERENCE		0.4
	CHARACTERISTIC_CALL_PRONE				0.2
	CHARACTERISTIC_BEDDY_BYE_TIME			0.2
	CHARACTERISTIC_EYE_COR_DEVICE			0.2
	CHARACTERISTIC_GAMMA_CORRECTION		0.2
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_CONTROLTYPE				1
} //end character java
