//===========================================================================
//
// Name:				laura_c.c
// Function:		characteristics for Laura Craft
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990518a
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "laura" //heh heh..like eidos will like this parody
{
	CHARACTERISTIC_NAME						"Laura Craft"
	CHARACTERISTIC_ALT_NAME					"Upsilon"
	CHARACTERISTIC_GENDER					"female"
	CHARACTERISTIC_CHAT_FILE				"bots/laura_t.c"
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/laura_w.c"
	CHARACTERISTIC_ITEMWEIGHTS				"bots/laura_i.c"
	CHARACTERISTIC_REACTIONTIME			0.70
	CHARACTERISTIC_ATTACK_SKILL			0.30
	CHARACTERISTIC_AIM_SKILL				0.3
	CHARACTERISTIC_AIM_ACCURACY			0.30
	CHARACTERISTIC_VIEW_ACCELERATION		300
	CHARACTERISTIC_VIEW_DEACCELERATION	300
	CHARACTERISTIC_CROUCHER					0.11
	CHARACTERISTIC_JUMPER					0.88
	CHARACTERISTIC_WEAPONJUMPING			1
	CHARACTERISTIC_GRAPPLE_USER			0.3
	CHARACTERISTIC_VENGEFULNESS			0.5
	CHARACTERISTIC_AGGRESSION				0.21
	CHARACTERISTIC_FEAR						0.1
	CHARACTERISTIC_SELFPRESERVATION		0.88
	CHARACTERISTIC_BUTTKISSER				0
	CHARACTERISTIC_FRUSTRATEDNESS			0.12
	CHARACTERISTIC_EASY_FRAGGER			0.1
	CHARACTERISTIC_ALERTNESS				0.99
	CHARACTERISTIC_TELEFRAGAWARE			0.81
	CHARACTERISTIC_CAMPER					0.21
	CHARACTERISTIC_EGO						0.34
	CHARACTERISTIC_TEAMSPIRIT				0.65
	CHARACTERISTIC_WEAPONSWITCHER			0.34
	CHARACTERISTIC_SKIN_SWITCHER			0.77
	CHARACTERISTIC_NAME_SWITCHER			0.34
//===========================================================================
	CHARACTERISTIC_CHAT_NAME				"laura"
	CHARACTERISTIC_CHAT_CPM					90
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.50
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.4
	CHARACTERISTIC_CHAT_REPLY				0.34
	CHARACTERISTIC_CHAT_DEATH				0.78
	CHARACTERISTIC_CHAT_KILL				0.9
	CHARACTERISTIC_CHAT_INSULT				0.5
	CHARACTERISTIC_CHAT_MISC				0.7
	CHARACTERISTIC_CHAT_RANDOM				0.22
//===========================================================================
	CHARACTERISTIC_PIZZAPREFERENCE		0.03
	CHARACTERISTIC_CALL_PRONE				0
	CHARACTERISTIC_BEDDY_BYE_TIME			0
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_CONTROLTYPE				1
} //end character laura
