//===========================================================================
//
// Name:				luuzr_c.c
// Function:		characteristics for bots
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990518b
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "luuzr"
{
	CHARACTERISTIC_NAME						"Luuzr"
	CHARACTERISTIC_ALT_NAME					"Eta"
	CHARACTERISTIC_GENDER					"male"
	CHARACTERISTIC_CHAT_FILE				"bots/luuzr_t.c"
//	CHARACTERISTIC_WEAPONWEIGHTS			"bots/luuzr_w.c"
	CHARACTERISTIC_WEAPONWEIGHTS			"default/defaul_w.c"
//	CHARACTERISTIC_ITEMWEIGHTS				"bots/luuzr_i.c"
	CHARACTERISTIC_ITEMWEIGHTS				"default/defaul_i.c"
	CHARACTERISTIC_REACTIONTIME			0.9
	CHARACTERISTIC_ATTACK_SKILL			0.1
	CHARACTERISTIC_AIM_SKILL				0.1
	CHARACTERISTIC_AIM_ACCURACY			0.1
	CHARACTERISTIC_VIEW_ACCELERATION		100
	CHARACTERISTIC_VIEW_DEACCELERATION	100
	CHARACTERISTIC_CROUCHER					0.6
	CHARACTERISTIC_JUMPER					0.2
	CHARACTERISTIC_WEAPONJUMPING			0.35
	CHARACTERISTIC_GRAPPLE_USER			0.1
	CHARACTERISTIC_VENGEFULNESS			1
	CHARACTERISTIC_AGGRESSION				0.50
	CHARACTERISTIC_FEAR						0.1
	CHARACTERISTIC_SELFPRESERVATION		0.001
	CHARACTERISTIC_BUTTKISSER				1
	CHARACTERISTIC_FRUSTRATEDNESS			1
	CHARACTERISTIC_EASY_FRAGGER			1
	CHARACTERISTIC_ALERTNESS				0.45
	CHARACTERISTIC_TELEFRAGAWARE			0.65
	CHARACTERISTIC_CAMPER					0.55
	CHARACTERISTIC_EGO						0.0001
	CHARACTERISTIC_TEAMSPIRIT				1
	CHARACTERISTIC_WEAPONSWITCHER			1
	CHARACTERISTIC_SKIN_SWITCHER			1
	CHARACTERISTIC_NAME_SWITCHER			1
//===========================================================================
	CHARACTERISTIC_CHAT_NAME				"luuzr"
	CHARACTERISTIC_CHAT_CPM					70
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.2
	CHARACTERISTIC_CHAT_REPLY				0.7
	CHARACTERISTIC_CHAT_DEATH				0.1
	CHARACTERISTIC_CHAT_KILL				0.8
	CHARACTERISTIC_CHAT_INSULT				0.57
	CHARACTERISTIC_CHAT_MISC				0.1
	CHARACTERISTIC_CHAT_RANDOM				0.11
//===========================================================================
	CHARACTERISTIC_PIZZAPREFERENCE		0.45
	CHARACTERISTIC_CALL_PRONE				0
	CHARACTERISTIC_BEDDY_BYE_TIME			0
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0
	CHARACTERISTIC_3DACCELERATOR			0
	CHARACTERISTIC_SOUNDTYPE				0
	CHARACTERISTIC_CONTROLTYPE				0
} //end character luuzr

