//===========================================================================
//
// Name:				maxine_c.c
// Function:		characteristics for Maxine
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990518b
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "maxine"
{
	CHARACTERISTIC_NAME						"Maxine"
	CHARACTERISTIC_ALT_NAME					"Mu"
	CHARACTERISTIC_GENDER					"female"
	CHARACTERISTIC_CHAT_FILE				"bots/maxine_t.c"
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/maxine_w.c"
	CHARACTERISTIC_ITEMWEIGHTS				"bots/maxine_i.c"
	CHARACTERISTIC_REACTIONTIME			0.75
	CHARACTERISTIC_ATTACK_SKILL			0.25
	CHARACTERISTIC_AIM_SKILL				0.8
	CHARACTERISTIC_AIM_ACCURACY			0.5
	CHARACTERISTIC_VIEW_ACCELERATION		700
	CHARACTERISTIC_VIEW_DEACCELERATION	900
	CHARACTERISTIC_CROUCHER					0.02
	CHARACTERISTIC_JUMPER					1
	CHARACTERISTIC_WEAPONJUMPING			1
	CHARACTERISTIC_GRAPPLE_USER			1
	CHARACTERISTIC_VENGEFULNESS			0.44
	CHARACTERISTIC_AGGRESSION				0.50
	CHARACTERISTIC_FEAR						0.10
	CHARACTERISTIC_SELFPRESERVATION		0.6
	CHARACTERISTIC_BUTTKISSER				0.74
	CHARACTERISTIC_FRUSTRATEDNESS			0.5
	CHARACTERISTIC_EASY_FRAGGER			0.45
	CHARACTERISTIC_ALERTNESS				1
	CHARACTERISTIC_TELEFRAGAWARE			0.3
	CHARACTERISTIC_CAMPER					0.2
	CHARACTERISTIC_EGO						0.1
	CHARACTERISTIC_TEAMSPIRIT				0.2
	CHARACTERISTIC_WEAPONSWITCHER			0
	CHARACTERISTIC_SKIN_SWITCHER			0.2
	CHARACTERISTIC_NAME_SWITCHER			0.01
//===========================================================================
	CHARACTERISTIC_CHAT_NAME				"maxine"
	CHARACTERISTIC_CHAT_CPM					97
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.75
	CHARACTERISTIC_CHAT_STARTENDLEVEL	1
	CHARACTERISTIC_CHAT_REPLY				0.7
	CHARACTERISTIC_CHAT_DEATH				0.76
	CHARACTERISTIC_CHAT_KILL				0.99
	CHARACTERISTIC_CHAT_INSULT				0.5
	CHARACTERISTIC_CHAT_MISC				0.5
	CHARACTERISTIC_CHAT_RANDOM				0.3
//===========================================================================
	CHARACTERISTIC_PIZZAPREFERENCE		0.2
	CHARACTERISTIC_CALL_PRONE				0.5
	CHARACTERISTIC_BEDDY_BYE_TIME			0.03
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_CONTROLTYPE				1
} //end character Maxine

