//===========================================================================
//
// Name:				messia_c.c
// Function:		characteristics for Shotgun Messiah
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990518b
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "messiah"
{
	CHARACTERISTIC_NAME						"Shotgun Messiah"
	CHARACTERISTIC_ALT_NAME					"Delta"
	CHARACTERISTIC_GENDER					"female"
	CHARACTERISTIC_CHAT_FILE				"bots/messia_t.c"
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/messia_w.c"
	CHARACTERISTIC_ITEMWEIGHTS				"bots/messia_i.c"
	CHARACTERISTIC_REACTIONTIME			0.40
	CHARACTERISTIC_ATTACK_SKILL			0.60
	CHARACTERISTIC_AIM_SKILL				0.60
	CHARACTERISTIC_AIM_ACCURACY			0.60
	CHARACTERISTIC_VIEW_ACCELERATION		360
	CHARACTERISTIC_VIEW_DEACCELERATION	440
	CHARACTERISTIC_CROUCHER					0.15
	CHARACTERISTIC_JUMPER					0.65
	CHARACTERISTIC_WEAPONJUMPING			0.3
	CHARACTERISTIC_GRAPPLE_USER			1
	CHARACTERISTIC_VENGEFULNESS			0.60
	CHARACTERISTIC_AGGRESSION				0.50
	CHARACTERISTIC_FEAR						0.10
	CHARACTERISTIC_SELFPRESERVATION		0.25
	CHARACTERISTIC_BUTTKISSER				0
	CHARACTERISTIC_FRUSTRATEDNESS			0.5
	CHARACTERISTIC_EASY_FRAGGER			0.9
	CHARACTERISTIC_ALERTNESS				0.45
	CHARACTERISTIC_TELEFRAGAWARE			0.8
	CHARACTERISTIC_CAMPER					0.5
	CHARACTERISTIC_EGO						0.6
	CHARACTERISTIC_TEAMSPIRIT				0.3
	CHARACTERISTIC_WEAPONSWITCHER			0.3
	CHARACTERISTIC_SKIN_SWITCHER			0
	CHARACTERISTIC_NAME_SWITCHER			0
//===========================================================================
	CHARACTERISTIC_CHAT_NAME				"messiah"
	CHARACTERISTIC_CHAT_CPM					130
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.60
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.61
	CHARACTERISTIC_CHAT_REPLY				0.43
	CHARACTERISTIC_CHAT_DEATH				0.62
	CHARACTERISTIC_CHAT_KILL				0.80
	CHARACTERISTIC_CHAT_INSULT				0.50
	CHARACTERISTIC_CHAT_MISC				0.40
	CHARACTERISTIC_CHAT_RANDOM				0.4
//===========================================================================
	CHARACTERISTIC_PIZZAPREFERENCE		0
	CHARACTERISTIC_CALL_PRONE				0.5
	CHARACTERISTIC_BEDDY_BYE_TIME			0.02
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0.7
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_CONTROLTYPE				2
} //end character messiah
