
//===========================================================================
//
// Name:				no9_c.c
// Function:		characteristics for bots
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990511a
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "no9"
{
	CHARACTERISTIC_NAME						"Number 9"
	CHARACTERISTIC_ALT_NAME					"Rho"
	CHARACTERISTIC_GENDER					"other"
	CHARACTERISTIC_CHAT_FILE				"bots/no9_t.c"
	CHARACTERISTIC_WEAPONWEIGHTS			"default/defaul_w.c"
//	CHARACTERISTIC_WEAPONWEIGHTS			"bots/no9_w.c"
	CHARACTERISTIC_ITEMWEIGHTS				"default/defaul_i.c"
//	CHARACTERISTIC_ITEMWEIGHTS				"bots/no9_i.c"
	CHARACTERISTIC_REACTIONTIME			0.25
	CHARACTERISTIC_ATTACK_SKILL			0.75
	CHARACTERISTIC_AIM_SKILL				0.75
	CHARACTERISTIC_AIM_ACCURACY			0.75
	CHARACTERISTIC_VIEW_ACCELERATION		300
	CHARACTERISTIC_VIEW_DEACCELERATION	310
	CHARACTERISTIC_CROUCHER					0.1
	CHARACTERISTIC_JUMPER					0.67
	CHARACTERISTIC_WEAPONJUMPING			0.67
	CHARACTERISTIC_GRAPPLE_USER			0.75
	CHARACTERISTIC_VENGEFULNESS			0.67
	CHARACTERISTIC_AGGRESSION				0.67
	CHARACTERISTIC_FEAR						0.1
	CHARACTERISTIC_SELFPRESERVATION		0.67
	CHARACTERISTIC_BUTTKISSER				0
	CHARACTERISTIC_FRUSTRATEDNESS			0.5
	CHARACTERISTIC_EASY_FRAGGER			0.9
	CHARACTERISTIC_ALERTNESS				0.45
	CHARACTERISTIC_TELEFRAGAWARE			0.67
	CHARACTERISTIC_CAMPER					0.01
	CHARACTERISTIC_EGO						0.75
	CHARACTERISTIC_TEAMSPIRIT				0.67
	CHARACTERISTIC_WEAPONSWITCHER			0.35
	CHARACTERISTIC_SKIN_SWITCHER			0.67
	CHARACTERISTIC_NAME_SWITCHER			0.67
//===========================================================================
	CHARACTERISTIC_CHAT_NAME				"no9"
	CHARACTERISTIC_CHAT_CPM					67
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.67
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.67
	CHARACTERISTIC_CHAT_REPLY				0.67
	CHARACTERISTIC_CHAT_DEATH				0.67
	CHARACTERISTIC_CHAT_KILL				0.67
	CHARACTERISTIC_CHAT_INSULT				0.67
	CHARACTERISTIC_CHAT_MISC				0.67
	CHARACTERISTIC_CHAT_RANDOM				0.67
//===========================================================================
	CHARACTERISTIC_PIZZAPREFERENCE		0
	CHARACTERISTIC_CALL_PRONE				0.5
	CHARACTERISTIC_BEDDY_BYE_TIME			0.02
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0.7
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_CONTROLTYPE				2
} //end character messiah

/*
	//
	CHARACTERISTIC_FRUSTRATEDNESS			0.2
	CHARACTERISTIC_EASY_FRAGGER			0.33
	CHARACTERISTIC_ALERTNESS				0.67
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_CONTROLTYPE				1
	CHARACTERISTIC_TEAMSPIRIT				0.67
	CHARACTERISTIC_PIZZAPREFERENCE		0.33
	CHARACTERISTIC_CALL_PRONE				0
	CHARACTERISTIC_BEDDY_BYE_TIME			0
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0
	CHARACTERISTIC_BUTTKISSER				0
} //end character no9*/

