//===========================================================================
//
// Name:				omicro.c
// Function:		characteristics for the demigoddess
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
// version:			19990511a by Squatt)
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "omicron"
{
	CHARACTERISTIC_NAME						"Demigoddess"
	CHARACTERISTIC_ALT_NAME					"Omicron"
	CHARACTERISTIC_GENDER					"female"
	CHARACTERISTIC_ATTACK_SKILL			0.95
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/omicro_w.c"
	CHARACTERISTIC_WEAPONSWITCHER			0.95
	CHARACTERISTIC_AIM_SKILL				0.95
	CHARACTERISTIC_AIM_ACCURACY			0.95
	CHARACTERISTIC_VIEW_ACCELERATION		1000//degrees per second, maximum 1800
	CHARACTERISTIC_VIEW_DEACCELERATION	1800
	CHARACTERISTIC_REACTIONTIME			0.05
	//
	CHARACTERISTIC_CHAT_FILE				"bots/omicro_t.c"
	CHARACTERISTIC_CHAT_NAME				"omicron"
	CHARACTERISTIC_CHAT_CPM					1000 //type wonder
	CHARACTERISTIC_CHAT_REPLY				0.55
	CHARACTERISTIC_CHAT_DEATH				0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.65
	CHARACTERISTIC_CHAT_INSULT				0.5
	CHARACTERISTIC_CHAT_KILL				0.75
	CHARACTERISTIC_CHAT_MISC				0.35
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.99
	CHARACTERISTIC_CHAT_RANDOM				0.12
	//
	CHARACTERISTIC_CROUCHER					0
	CHARACTERISTIC_JUMPER					0.95
	CHARACTERISTIC_WEAPONJUMPING			0.95 //likes weaponjumpimg
	CHARACTERISTIC_GRAPPLE_USER			0.99
	//
	CHARACTERISTIC_ITEMWEIGHTS				"bots/omicro_i.c"
//	CHARACTERISTIC_HEALTHGATHERER			0.95
//	CHARACTERISTIC_ARMORGATHERER			0.95
	CHARACTERISTIC_TELEFRAGAWARE			0.95
	CHARACTERISTIC_AGGRESSION				0.95
	CHARACTERISTIC_FEAR						0.05
	CHARACTERISTIC_SELFPRESERVATION		0.95
	CHARACTERISTIC_VENGEFULNESS			0.95
	CHARACTERISTIC_CAMPER					0.3
	CHARACTERISTIC_EGO						0.95
	//
	CHARACTERISTIC_FAVCLASS					0
	CHARACTERISTIC_SKIN_SWITCHER			0
	CHARACTERISTIC_NAME_SWITCHER			0
	CHARACTERISTIC_FRUSTRATEDTEEN			0
	CHARACTERISTIC_FRUSTRATEDNESS			0
	CHARACTERISTIC_EASY_FRAGGER			0
	CHARACTERISTIC_ALERTNESS				0.95
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_CONTROLTYPE				1
	CHARACTERISTIC_TEAMSPIRIT				0.95
	CHARACTERISTIC_PIZZAPREFERENCE		0
	CHARACTERISTIC_CALL_PRONE				0.5
	CHARACTERISTIC_BEDDY_BYE_TIME			0.01
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0.6
	CHARACTERISTIC_BUTTKISSER				0
} //end character omicron

