//===========================================================================
//
// Name:				player_c.c
// Function:		characteristics for player bot character
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990511b
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "player"
{
	CHARACTERISTIC_NAME						"player"
	CHARACTERISTIC_ALT_NAME					"Pi"
	CHARACTERISTIC_GENDER					"male"
	CHARACTERISTIC_CHAT_FILE				"bots/player_t.c"
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/player_w.c"
	CHARACTERISTIC_ITEMWEIGHTS				"bots/player_i.c"
	//
	CHARACTERISTIC_ATTACK_SKILL			0.25
	//
	CHARACTERISTIC_WEAPONSWITCHER			0
	CHARACTERISTIC_AIM_SKILL				0.25
	CHARACTERISTIC_AIM_ACCURACY			0.25
	CHARACTERISTIC_VIEW_ACCELERATION		150
	CHARACTERISTIC_VIEW_DEACCELERATION	200
	CHARACTERISTIC_REACTIONTIME			0.75
	//
	CHARACTERISTIC_CHAT_NAME				"player"
	CHARACTERISTIC_CHAT_CPM					90
	CHARACTERISTIC_CHAT_REPLY				0.5
	CHARACTERISTIC_CHAT_DEATH				0.35
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0
	CHARACTERISTIC_CHAT_INSULT				0.5
	CHARACTERISTIC_CHAT_KILL				0.3
	CHARACTERISTIC_CHAT_MISC				0.3
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0
	CHARACTERISTIC_CHAT_RANDOM				0.24
	//
	CHARACTERISTIC_CROUCHER					1
	CHARACTERISTIC_JUMPER					0.3
	CHARACTERISTIC_WEAPONJUMPING			0
	CHARACTERISTIC_GRAPPLE_USER			0.38
	//
//	CHARACTERISTIC_HEALTHGATHERER			0.75
//	CHARACTERISTIC_ARMORGATHERER			0.25
	CHARACTERISTIC_TELEFRAGAWARE			0.1
	CHARACTERISTIC_AGGRESSION				0.3
	CHARACTERISTIC_FEAR						0.9
	CHARACTERISTIC_SELFPRESERVATION		0.6
	CHARACTERISTIC_VENGEFULNESS			0.8
	CHARACTERISTIC_CAMPER					0.5
	CHARACTERISTIC_EGO						0.25
	//
	CHARACTERISTIC_FAVCLASS					0
	CHARACTERISTIC_SKIN_SWITCHER			0.7
	CHARACTERISTIC_NAME_SWITCHER			0.01
	CHARACTERISTIC_FRUSTRATEDTEEN			0.5
	CHARACTERISTIC_FRUSTRATEDNESS			0.5
	CHARACTERISTIC_EASY_FRAGGER			1
	CHARACTERISTIC_ALERTNESS				0.3
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_3DACCELERATOR			0
	CHARACTERISTIC_CONTROLTYPE				1
	CHARACTERISTIC_TEAMSPIRIT				0.2
	CHARACTERISTIC_PIZZAPREFERENCE		0.65
	CHARACTERISTIC_CALL_PRONE				0.5
	CHARACTERISTIC_BEDDY_BYE_TIME			0.3
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0
	CHARACTERISTIC_BUTTKISSER				0
} //end character player

