//===========================================================================
//
// Name:				reaper_c.c
// Function:		characteristics for the Reaper Bot character
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990510a
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "reaper" //heh heh  :)
{
	CHARACTERISTIC_NAME						"Reaper"
	CHARACTERISTIC_ALT_NAME					"Reaper"
	CHARACTERISTIC_GENDER					"other"
	CHARACTERISTIC_ATTACK_SKILL			1
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/reaper_w.c"
	CHARACTERISTIC_WEAPONSWITCHER			0.70
	CHARACTERISTIC_AIM_SKILL				1
	CHARACTERISTIC_AIM_ACCURACY			1
	CHARACTERISTIC_VIEW_ACCELERATION		1800
	CHARACTERISTIC_VIEW_DEACCELERATION	1800
	CHARACTERISTIC_REACTIONTIME			0
	//
	CHARACTERISTIC_CHAT_FILE				"bots/reaper_t.c"
	CHARACTERISTIC_CHAT_NAME				"reaper"
	CHARACTERISTIC_CHAT_CPM					1000  //still, he's not the talkative sort
	CHARACTERISTIC_CHAT_REPLY				0.7
	CHARACTERISTIC_CHAT_DEATH				0.7
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.7
	CHARACTERISTIC_CHAT_INSULT				1
	CHARACTERISTIC_CHAT_KILL				0.9
	CHARACTERISTIC_CHAT_MISC				0.4
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.9
	CHARACTERISTIC_CHAT_RANDOM				0.1
	//
	CHARACTERISTIC_CROUCHER					0
	CHARACTERISTIC_JUMPER					1
	CHARACTERISTIC_WEAPONJUMPING			0.8
	CHARACTERISTIC_GRAPPLE_USER			1
	//
//	CHARACTERISTIC_ITEMWEIGHTS				"bots/defaul_i.c"
	CHARACTERISTIC_ITEMWEIGHTS				"bots/reaper_i.c"
	CHARACTERISTIC_HEALTHGATHERER			1
	CHARACTERISTIC_ARMORGATHERER			1
	CHARACTERISTIC_TELEFRAGAWARE			1
	CHARACTERISTIC_AGGRESSION				1
	CHARACTERISTIC_FEAR						0.01
	CHARACTERISTIC_SELFPRESERVATION		0.1
	CHARACTERISTIC_VENGEFULNESS			0.1
	CHARACTERISTIC_CAMPER					0.1
	CHARACTERISTIC_EGO						1
	//
	CHARACTERISTIC_FAVCLASS					0
	CHARACTERISTIC_SKIN_SWITCHER			0
	CHARACTERISTIC_NAME_SWITCHER			0
	CHARACTERISTIC_FRUSTRATEDTEEN			0
	CHARACTERISTIC_FRUSTRATEDNESS			0
	CHARACTERISTIC_EASY_FRAGGER			0.5
	CHARACTERISTIC_ALERTNESS				1
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_CONTROLTYPE				2
	CHARACTERISTIC_TEAMSPIRIT				0
	CHARACTERISTIC_PIZZAPREFERENCE		0
	CHARACTERISTIC_CALL_PRONE				0
	CHARACTERISTIC_BEDDY_BYE_TIME			0
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0
	CHARACTERISTIC_BUTTKISSER				666
} //end character reaper

