//===========================================================================
//
// Name:				sparta_c.c
// Function:		characteristics for bots
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990130a
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "spartacus"
{
	CHARACTERISTIC_NAME						"Spartacus"
	CHARACTERISTIC_ALT_NAME					"Sigma"
	CHARACTERISTIC_GENDER					"male"
	CHARACTERISTIC_ATTACK_SKILL			0.5
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/sparta_w.c"
	CHARACTERISTIC_WEAPONSWITCHER			0
	CHARACTERISTIC_AIM_SKILL				0.5
	CHARACTERISTIC_AIM_ACCURACY			0.5
	CHARACTERISTIC_VIEW_ACCELERATION		200
	CHARACTERISTIC_VIEW_DEACCELERATION	200
	CHARACTERISTIC_REACTIONTIME			0.5
	//
	CHARACTERISTIC_CHAT_FILE				"bots/sparta_t.c"
	CHARACTERISTIC_CHAT_NAME				"spartacus"
	CHARACTERISTIC_CHAT_CPM					116
	CHARACTERISTIC_CHAT_REPLY				0.9
	CHARACTERISTIC_CHAT_DEATH				1
	CHARACTERISTIC_CHAT_ENTEREXITGAME	1
	CHARACTERISTIC_CHAT_INSULT				0.2
	CHARACTERISTIC_CHAT_KILL				1
	CHARACTERISTIC_CHAT_MISC				1
	CHARACTERISTIC_CHAT_STARTENDLEVEL	1
	CHARACTERISTIC_CHAT_RANDOM				0.31
	//
	CHARACTERISTIC_CROUCHER					0.26
	CHARACTERISTIC_JUMPER					0.9
	CHARACTERISTIC_WEAPONJUMPING			0.1
	CHARACTERISTIC_GRAPPLE_USER			0.5
	//
	CHARACTERISTIC_ITEMWEIGHTS				"default/defaul_i.c"
//	CHARACTERISTIC_ITEMWEIGHTS				"bots/sparta_i.c"
	CHARACTERISTIC_HEALTHGATHERER			0.85
	CHARACTERISTIC_ARMORGATHERER			1
	CHARACTERISTIC_TELEFRAGAWARE			0.75
	CHARACTERISTIC_AGGRESSION				1
	CHARACTERISTIC_FEAR						0.4
	CHARACTERISTIC_SELFPRESERVATION		0.44
	CHARACTERISTIC_VENGEFULNESS			0.2
	CHARACTERISTIC_CAMPER					0.25
	CHARACTERISTIC_EGO						0.5
	//
	CHARACTERISTIC_FAVCLASS					0
	CHARACTERISTIC_SKIN_SWITCHER			0
	CHARACTERISTIC_NAME_SWITCHER			0.01
	CHARACTERISTIC_FRUSTRATEDTEEN			0
	CHARACTERISTIC_FRUSTRATEDNESS			0
	CHARACTERISTIC_EASY_FRAGGER			0.2
	CHARACTERISTIC_ALERTNESS				1
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_CONTROLTYPE				0
	CHARACTERISTIC_TEAMSPIRIT				1
	CHARACTERISTIC_PIZZAPREFERENCE		0.1
	CHARACTERISTIC_CALL_PRONE				0.2
	CHARACTERISTIC_BEDDY_BYE_TIME			0.1
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0
	CHARACTERISTIC_BUTTKISSER				0
} //end character spartacus

