//===========================================================================
//
// Name:				chars.c
// Function:		characteristics for bots
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990130a
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "stud"
{
	CHARACTERISTIC_NAME						"Steroid Stud"
	CHARACTERISTIC_ALT_NAME					"Tau"
	CHARACTERISTIC_GENDER					"male"
	CHARACTERISTIC_ATTACK_SKILL			0.2
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/stud_w.c"
	CHARACTERISTIC_WEAPONSWITCHER			0
	CHARACTERISTIC_AIM_SKILL				0.2
	CHARACTERISTIC_AIM_ACCURACY			0.2
	CHARACTERISTIC_VIEW_ACCELERATION		100
	CHARACTERISTIC_VIEW_DEACCELERATION	100
	CHARACTERISTIC_REACTIONTIME			0.8
	//
	CHARACTERISTIC_CHAT_FILE				"bots/stud_t.c"
	CHARACTERISTIC_CHAT_NAME				"stud"
	CHARACTERISTIC_CHAT_CPM					127
	CHARACTERISTIC_CHAT_REPLY				0.9
	CHARACTERISTIC_CHAT_DEATH				0.1
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.1
	CHARACTERISTIC_CHAT_INSULT				0.1
	CHARACTERISTIC_CHAT_KILL				0.9
	CHARACTERISTIC_CHAT_MISC				0.1
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.1
	CHARACTERISTIC_CHAT_RANDOM				0.1
	//
	CHARACTERISTIC_CROUCHER					0.05
	CHARACTERISTIC_JUMPER					1
	CHARACTERISTIC_WEAPONJUMPING			0.1
	CHARACTERISTIC_GRAPPLE_USER			0.2
	//
	CHARACTERISTIC_ITEMWEIGHTS				"default/defaul_i.c"
//	CHARACTERISTIC_ITEMWEIGHTS				"bots/stud_i.c"
	CHARACTERISTIC_HEALTHGATHERER			0.1
	CHARACTERISTIC_ARMORGATHERER			0.1
	CHARACTERISTIC_TELEFRAGAWARE			0.1
	CHARACTERISTIC_AGGRESSION				0.1
	CHARACTERISTIC_FEAR						0.1
	CHARACTERISTIC_SELFPRESERVATION		0.1
	CHARACTERISTIC_VENGEFULNESS			0.9
	CHARACTERISTIC_CAMPER					0.9
	CHARACTERISTIC_EGO						0.2
	//
	CHARACTERISTIC_FAVCLASS					0
	CHARACTERISTIC_SKIN_SWITCHER			0.9
	CHARACTERISTIC_NAME_SWITCHER			0.19
	CHARACTERISTIC_FRUSTRATEDTEEN			0.11
	CHARACTERISTIC_FRUSTRATEDNESS			0.12
	CHARACTERISTIC_EASY_FRAGGER			0.15
	CHARACTERISTIC_ALERTNESS				0.18
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_CONTROLTYPE				1
	CHARACTERISTIC_TEAMSPIRIT				0.8
	CHARACTERISTIC_PIZZAPREFERENCE		0
	CHARACTERISTIC_CALL_PRONE				0
	CHARACTERISTIC_BEDDY_BYE_TIME			0
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0
	CHARACTERISTIC_BUTTKISSER				0
} //end character stud

