//===========================================================================
//
// Name:				trash_c.c
// Function:		characteristics for Trash bot character
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990511a
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "trash"
{
	CHARACTERISTIC_NAME						"Trash"
	CHARACTERISTIC_ALT_NAME					"Omega"
	CHARACTERISTIC_GENDER					"cyborg"
	CHARACTERISTIC_ATTACK_SKILL			0.80
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/trash_w.c"
	CHARACTERISTIC_WEAPONSWITCHER			0.55
	CHARACTERISTIC_AIM_SKILL				0.8
	CHARACTERISTIC_AIM_ACCURACY			0.8
	CHARACTERISTIC_VIEW_ACCELERATION		200
	CHARACTERISTIC_VIEW_DEACCELERATION	200
	CHARACTERISTIC_REACTIONTIME			0.20
	//
	CHARACTERISTIC_CHAT_FILE				"bots/trash_t.c"
	CHARACTERISTIC_CHAT_NAME				"trash"
	CHARACTERISTIC_CHAT_CPM					20
	CHARACTERISTIC_CHAT_REPLY				0.57
	CHARACTERISTIC_CHAT_DEATH				0.01
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.6
	CHARACTERISTIC_CHAT_INSULT				0.35
	CHARACTERISTIC_CHAT_KILL				0.65
	CHARACTERISTIC_CHAT_MISC				0.95
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.3
	CHARACTERISTIC_CHAT_RANDOM				0.25
	//
	CHARACTERISTIC_CROUCHER					0.01
	CHARACTERISTIC_JUMPER					0.45
	CHARACTERISTIC_WEAPONJUMPING			0.80
	CHARACTERISTIC_GRAPPLE_USER			0.80
	//
	CHARACTERISTIC_ITEMWEIGHTS				"bots/trash_i.c"
//	CHARACTERISTIC_HEALTHGATHERER			0.45
//	CHARACTERISTIC_ARMORGATHERER			0.55
	CHARACTERISTIC_TELEFRAGAWARE			0.35
	CHARACTERISTIC_AGGRESSION				0.65
	CHARACTERISTIC_FEAR						0.95
	CHARACTERISTIC_SELFPRESERVATION		0.85
	CHARACTERISTIC_VENGEFULNESS			0.95
	CHARACTERISTIC_CAMPER					0.65
	CHARACTERISTIC_EGO						0.2
	//
	CHARACTERISTIC_FAVCLASS					0
	CHARACTERISTIC_SKIN_SWITCHER			0.8
	CHARACTERISTIC_NAME_SWITCHER			0.01
	CHARACTERISTIC_FRUSTRATEDTEEN			0
	CHARACTERISTIC_FRUSTRATEDNESS			0.05
	CHARACTERISTIC_EASY_FRAGGER			0.2
	CHARACTERISTIC_ALERTNESS				0.45
	CHARACTERISTIC_SOUNDTYPE				1
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_CONTROLTYPE				1
	CHARACTERISTIC_TEAMSPIRIT				1
	CHARACTERISTIC_PIZZAPREFERENCE		0.01
	CHARACTERISTIC_CALL_PRONE				0.2
	CHARACTERISTIC_BEDDY_BYE_TIME			0.1
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0
	CHARACTERISTIC_BUTTKISSER				0
} //end character trash


