//===========================================================================
//
// Name:				zero.c
// Function:		characteristics for Zero
// Programmer:		MrElusive(mrelusive@demigod.demon.nl)
//						B.D. Squatt (squatt@demigod.demon.nl) 
// version:			19990510a
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "zero"
{
	CHARACTERISTIC_NAME						"Zero"
	CHARACTERISTIC_ALT_NAME					"Kappa"
	CHARACTERISTIC_GENDER					"none"
	CHARACTERISTIC_CHAT_FILE				"bots/zero_t.c"
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/zero_w.c"
	CHARACTERISTIC_ITEMWEIGHTS				"bots/zero_i.c"
	CHARACTERISTIC_REACTIONTIME			1.5
	CHARACTERISTIC_ATTACK_SKILL			0.001
	CHARACTERISTIC_AIM_SKILL				0.001
	CHARACTERISTIC_AIM_ACCURACY			0.001
	CHARACTERISTIC_VIEW_ACCELERATION		670
	CHARACTERISTIC_VIEW_DEACCELERATION	800
	CHARACTERISTIC_CROUCHER					1
	CHARACTERISTIC_JUMPER					0.4
	CHARACTERISTIC_WEAPONJUMPING			0.55
	CHARACTERISTIC_GRAPPLE_USER			0.001
	CHARACTERISTIC_VENGEFULNESS			0.3
	CHARACTERISTIC_AGGRESSION				0.5
	CHARACTERISTIC_FEAR						0.1
	CHARACTERISTIC_SELFPRESERVATION		1
	CHARACTERISTIC_BUTTKISSER				0
	CHARACTERISTIC_FRUSTRATEDNESS			0.66
	CHARACTERISTIC_EASY_FRAGGER			0.6
	CHARACTERISTIC_ALERTNESS				0.22
	CHARACTERISTIC_TELEFRAGAWARE			0.34
	CHARACTERISTIC_CAMPER					1
	CHARACTERISTIC_EGO						0.6
	CHARACTERISTIC_TEAMSPIRIT				1
	CHARACTERISTIC_WEAPONSWITCHER			0.45
	CHARACTERISTIC_SKIN_SWITCHER			0.7
	CHARACTERISTIC_NAME_SWITCHER			0.9
//===========================================================================
	CHARACTERISTIC_CHAT_NAME				"zero"
	CHARACTERISTIC_CHAT_CPM					98
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.9
	CHARACTERISTIC_CHAT_STARTENDLEVEL	0.6
	CHARACTERISTIC_CHAT_REPLY				0.6
	CHARACTERISTIC_CHAT_DEATH				0.3
	CHARACTERISTIC_CHAT_KILL				1
	CHARACTERISTIC_CHAT_INSULT				1
	CHARACTERISTIC_CHAT_MISC				0.4
	CHARACTERISTIC_CHAT_RANDOM				0.34
//===========================================================================
	CHARACTERISTIC_PIZZAPREFERENCE		0
	CHARACTERISTIC_CALL_PRONE				0
	CHARACTERISTIC_BEDDY_BYE_TIME			0
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_SOUNDTYPE				0
	CHARACTERISTIC_CONTROLTYPE				1
} //end character zero


