

#define INVENTORY_NONE					0
//armor
#define INVENTORY_ARMORBODY			1
#define INVENTORY_ARMORCOMBAT			2
#define INVENTORY_ARMORJACKET			3
#define INVENTORY_ARMORSHARD			4
#define INVENTORY_POWERSCREEN			5
#define INVENTORY_POWERSHIELD			6
//weapons
#define INVENTORY_BLASTER				7
#define INVENTORY_SHOTGUN				8
#define INVENTORY_SUPERSHOTGUN		9
#define INVENTORY_MACHINEGUN			10
#define INVENTORY_CHAINGUN				11
#define INVENTORY_GRENADES				12
#define INVENTORY_GRENADELAUNCHER	13
#define INVENTORY_ROCKETLAUNCHER		14
#define INVENTORY_HYPERBLASTER		15
#define INVENTORY_RAILGUN				16
#define INVENTORY_BFG10K				17
//ammo
#define INVENTORY_SHELLS				18
#define INVENTORY_BULLETS				19
#define INVENTORY_CELLS					20
#define INVENTORY_ROCKETS				21
#define INVENTORY_SLUGS					22
//powerups
#define INVENTORY_QUAD					23
#define INVENTORY_INVULNERABILITY	24
#define INVENTORY_SILENCER				25
#define INVENTORY_REBREATHER			26
#define INVENTORY_ENVIRONMENTSUIT	27
#define INVENTORY_ANCIENTHEAD			28
#define INVENTORY_ADRENALINE			29		//added to INVENTORY_HEALTH
#define INVENTORY_BANDOLIER			30
#define INVENTORY_AMMOPACK				31
//keys
#define INVENTORY_DATACD				32
#define INVENTORY_POWERCUBE			33
#define INVENTORY_PYRAMIDKEY			34
#define INVENTORY_DATASPINNER			35
#define INVENTORY_SECURITYPASS		36
#define INVENTORY_BLUEKEY				37
#define INVENTORY_REDKEY				38
#define INVENTORY_COMMANDERSHEAD		39
#define INVENTORY_AIRSTRIKEMARKER	40
//health
#define INVENTORY_HEALTH				41
//for ctf
#define INVENTORY_GRAPPLE				42		// Grapple Hook
#define INVENTORY_FLAG1					43		// Red Flag
#define INVENTORY_FLAG2					44		// Blue Flag
#define INVENTORY_TECH1					45		// Resistance Tech \ Disruptor Shield
#define INVENTORY_TECH2					46		// Strength Tech \ Power Amplifier
#define INVENTORY_TECH3					47		// Haste Tech \ Time Accel
#define INVENTORY_TECH4					48		// Regeneration Tech \ AutoDoc
//XATRIX
#define INVENTORY_IONRIPPER			49
#define INVENTORY_PHALANX				50
#define INVENTORY_MAGSLUGS				51
#define INVENTORY_TRAP					52
#define INVENTORY_DUALFIREDAMAGE		53
#define INVENTORY_GREENKEY				54
//ROGUE
#define INVENTORY_ETFRIFLE				55
#define INVENTORY_PROXLAUNCHER		56
#define INVENTORY_PLASMABEAM			57
#define INVENTORY_CHAINFIST			58
#define INVENTORY_DISRUPTOR			59
#define INVENTORY_FLECHETTES			60
#define INVENTORY_PROX					61
#define INVENTORY_TESLA					62
#define INVENTORY_AMBOMB				63
#define INVENTORY_ROUNDS				64
#define INVENTORY_IRGOGGLES			65
#define INVENTORY_DOUBLEDAMAGE		66
#define INVENTORY_COMPASS				67
#define INVENTORY_VENGEANCESPHERE	68
#define INVENTORY_HUNTERSPHERE		69
#define INVENTORY_DEFENDERSPHERE		70
#define INVENTORY_DOPPLEGANGER		71
#define INVENTORY_TAGTOKEN				72
#define INVENTORY_ANTIMATTERPOD		73
#define INVENTORY_ANTIMATTERBOMB		74
//enemy stuff
#define ENEMY_HORIZONTAL_DIST			200
#define ENEMY_HEIGHT						201
#define NUM_VISIBLE_ENEMIES			202
#define NUM_VISIBLE_TEAMMATES			203
//using powerups
#define USING_QUAD						204
#define USING_INVULNERABILITY			205
#define USING_SILENCER					206
#define USING_REBREATHER				207
#define USING_ENVIRONMENTSUIT			208
#define USING_ANCIENTHEAD				209
#define USING_POWERSCREEN				210
#define USING_POWERSHIELD				211
//using weapons
#define USING_BLASTER					215
#define USING_SHOTGUN					216
#define USING_SUPERSHOTGUN				217
#define USING_MACHINEGUN				218
#define USING_CHAINGUN					219
#define USING_GRENADELAUNCHER			220
#define USING_ROCKETLAUNCHER			221
#define USING_HYPERBLASTER				222
#define USING_RAILGUN					223
#define USING_BFG10K						224
#define USING_GRENADES					225
#define USING_GRAPPLE					226
//enemy using weapons
#define ENEMY_BLASTER					230
#define ENEMY_SHOTGUN					231
#define ENEMY_SUPERSHOTGUN				232
#define ENEMY_MACHINEGUN				233
#define ENEMY_CHAINGUN					234
#define ENEMY_GRENADELAUNCHER			235
#define ENEMY_ROCKETLAUNCHER			236
#define ENEMY_HYPERBLASTER				237
#define ENEMY_RAILGUN					238
#define ENEMY_BFG10K						239
#define ENEMY_GRENADES					240
#define ENEMY_GRAPPLE					241
//enemy using powerups
#define ENEMY_QUAD						245
#define ENEMY_INVULNERABILITY			246
#define ENEMY_POWERSCREEN				247
#define ENEMY_POWERSHIELD				248

