set(project_root "E:/Repositories/Gladiator-Bot-reverse")

if(DEFINED ENV{GLADIATOR_ASSET_DIR} AND NOT "$ENV{GLADIATOR_ASSET_DIR}" STREQUAL "")
    set(asset_root "$ENV{GLADIATOR_ASSET_DIR}")
else()
    set(asset_root "${project_root}/dev_tools/assets")
endif()

set(missing "")
macro(require_file description path)
    if(NOT EXISTS "${path}")
        list(APPEND missing "${description} (${path})")
    endif()
endmacro()

require_file("mover BSP" "${asset_root}/maps/test_mover.bsp")
require_file("mover AAS" "${asset_root}/maps/test_mover.aas")
require_file("precompiler lexer source (fw_items.c)" "${asset_root}/fw_items.c")
require_file("precompiler lexer source (syn.c)" "${asset_root}/syn.c")
require_file("weapon configuration stub (weapons.c)" "${asset_root}/weapons.c")
require_file("default weapon weights (defaul_w.c)" "${asset_root}/default/defaul_w.c")
require_file("default item weights (defaul_i.c)" "${asset_root}/default/defaul_i.c")

if(missing)
    message(STATUS "Parity asset verification failed:")
    foreach(entry IN LISTS missing)
        message(STATUS " - ${entry}")
    endforeach()
    message(FATAL_ERROR
        "Stage the listed assets under ${asset_root} (or set GLADIATOR_ASSET_DIR to the correct asset root) "
        "before rerunning the parity suite. See tests/README.md for download locations and layout requirements.")
endif()

message(STATUS "Parity assets verified: ${asset_root}")

if(NOT "$ENV{GLADIATOR_Q2_BASEDIR}" STREQUAL "" OR NOT "$ENV{GLADIATOR_Q2_DEDICATED_SERVER}" STREQUAL "")
    if("$ENV{GLADIATOR_Q2_BASEDIR}" STREQUAL "")
        message(STATUS "GLADIATOR_Q2_BASEDIR is unset; headless Quake II parity will skip.")
    else()
        set(require_q2 "")
        if(NOT IS_DIRECTORY "$ENV{GLADIATOR_Q2_BASEDIR}/baseq2")
            list(APPEND require_q2 "baseq2 asset directory ($ENV{GLADIATOR_Q2_BASEDIR}/baseq2)")
        endif()
        if(NOT EXISTS "$ENV{GLADIATOR_Q2_BASEDIR}/baseq2/pak0.pak")
            list(APPEND require_q2 "pak0.pak inside baseq2")
        endif()
        if(require_q2)
            message(STATUS "Quake II assets incomplete:")
            foreach(entry IN LISTS require_q2)
                message(STATUS " - ${entry}")
            endforeach()
        else()
            message(STATUS "Quake II assets detected at $ENV{GLADIATOR_Q2_BASEDIR}")
        endif()
    endif()
    if("$ENV{GLADIATOR_Q2_DEDICATED_SERVER}" STREQUAL "")
        message(STATUS "GLADIATOR_Q2_DEDICATED_SERVER is unset; headless Quake II parity will skip.")
    elseif(NOT EXISTS "$ENV{GLADIATOR_Q2_DEDICATED_SERVER}")
        message(STATUS "Quake II dedicated server missing or not executable: $ENV{GLADIATOR_Q2_DEDICATED_SERVER}")
    else()
        message(STATUS "Quake II dedicated server executable: $ENV{GLADIATOR_Q2_DEDICATED_SERVER}")
    endif()
else()
    message(STATUS
        "Headless Quake II parity assets not checked (set GLADIATOR_Q2_BASEDIR and GLADIATOR_Q2_DEDICATED_SERVER to validate).")
endif()
