# CMake generated Testfile for 
# Source directory: E:/Repositories/Gladiator-Bot-reverse/tests/tools
# Build directory: E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/tools
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bspc_filesystem "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/tools/Debug/bspc_filesystem_tests.exe")
  set_tests_properties(bspc_filesystem PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;19;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bspc_filesystem "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/tools/Release/bspc_filesystem_tests.exe")
  set_tests_properties(bspc_filesystem PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;19;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bspc_filesystem "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/tools/MinSizeRel/bspc_filesystem_tests.exe")
  set_tests_properties(bspc_filesystem PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;19;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bspc_filesystem "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/tools/RelWithDebInfo/bspc_filesystem_tests.exe")
  set_tests_properties(bspc_filesystem PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;19;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;0;")
else()
  add_test(bspc_filesystem NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bspc_cli_modes "C:/Python311/python.exe" "E:/Repositories/Gladiator-Bot-reverse/tools/bspc/run_cli_modes.py" "--bspc" "E:/Repositories/Gladiator-Bot-reverse/build-fable/tools/bspc/Debug/bspc.exe" "--workspace" "E:/Repositories/Gladiator-Bot-reverse/build-fable/test-output/bspc_cli")
  set_tests_properties(bspc_cli_modes PROPERTIES  WORKING_DIRECTORY "E:/Repositories/Gladiator-Bot-reverse" _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;22;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bspc_cli_modes "C:/Python311/python.exe" "E:/Repositories/Gladiator-Bot-reverse/tools/bspc/run_cli_modes.py" "--bspc" "E:/Repositories/Gladiator-Bot-reverse/build-fable/tools/bspc/Release/bspc.exe" "--workspace" "E:/Repositories/Gladiator-Bot-reverse/build-fable/test-output/bspc_cli")
  set_tests_properties(bspc_cli_modes PROPERTIES  WORKING_DIRECTORY "E:/Repositories/Gladiator-Bot-reverse" _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;22;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bspc_cli_modes "C:/Python311/python.exe" "E:/Repositories/Gladiator-Bot-reverse/tools/bspc/run_cli_modes.py" "--bspc" "E:/Repositories/Gladiator-Bot-reverse/build-fable/tools/bspc/MinSizeRel/bspc.exe" "--workspace" "E:/Repositories/Gladiator-Bot-reverse/build-fable/test-output/bspc_cli")
  set_tests_properties(bspc_cli_modes PROPERTIES  WORKING_DIRECTORY "E:/Repositories/Gladiator-Bot-reverse" _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;22;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bspc_cli_modes "C:/Python311/python.exe" "E:/Repositories/Gladiator-Bot-reverse/tools/bspc/run_cli_modes.py" "--bspc" "E:/Repositories/Gladiator-Bot-reverse/build-fable/tools/bspc/RelWithDebInfo/bspc.exe" "--workspace" "E:/Repositories/Gladiator-Bot-reverse/build-fable/test-output/bspc_cli")
  set_tests_properties(bspc_cli_modes PROPERTIES  WORKING_DIRECTORY "E:/Repositories/Gladiator-Bot-reverse" _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;22;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/tools/CMakeLists.txt;0;")
else()
  add_test(bspc_cli_modes NOT_AVAILABLE)
endif()
