# CMake generated Testfile for 
# Source directory: E:/Repositories/Gladiator-Bot-reverse/tests/bspc
# Build directory: E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/bspc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bspc_map_parser "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/bspc/Debug/bspc_map_parser_tests.exe")
  set_tests_properties(bspc_map_parser PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;26;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bspc_map_parser "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/bspc/Release/bspc_map_parser_tests.exe")
  set_tests_properties(bspc_map_parser PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;26;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bspc_map_parser "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/bspc/MinSizeRel/bspc_map_parser_tests.exe")
  set_tests_properties(bspc_map_parser PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;26;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bspc_map_parser "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/bspc/RelWithDebInfo/bspc_map_parser_tests.exe")
  set_tests_properties(bspc_map_parser PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;26;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;0;")
else()
  add_test(bspc_map_parser NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bspc_legacy "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/bspc/Debug/bspc_legacy_tests.exe")
  set_tests_properties(bspc_legacy PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;44;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bspc_legacy "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/bspc/Release/bspc_legacy_tests.exe")
  set_tests_properties(bspc_legacy PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;44;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bspc_legacy "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/bspc/MinSizeRel/bspc_legacy_tests.exe")
  set_tests_properties(bspc_legacy PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;44;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bspc_legacy "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/bspc/RelWithDebInfo/bspc_legacy_tests.exe")
  set_tests_properties(bspc_legacy PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;44;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;0;")
else()
  add_test(bspc_legacy NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bspc_world_loader "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/bspc/Debug/bspc_world_loader_tests.exe")
  set_tests_properties(bspc_world_loader PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;73;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bspc_world_loader "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/bspc/Release/bspc_world_loader_tests.exe")
  set_tests_properties(bspc_world_loader PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;73;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bspc_world_loader "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/bspc/MinSizeRel/bspc_world_loader_tests.exe")
  set_tests_properties(bspc_world_loader PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;73;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bspc_world_loader "E:/Repositories/Gladiator-Bot-reverse/build-fable/tests/bspc/RelWithDebInfo/bspc_world_loader_tests.exe")
  set_tests_properties(bspc_world_loader PROPERTIES  _BACKTRACE_TRIPLES "E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;73;add_test;E:/Repositories/Gladiator-Bot-reverse/tests/bspc/CMakeLists.txt;0;")
else()
  add_test(bspc_world_loader NOT_AVAILABLE)
endif()
